# Generated by Django 5.2.8 on 2025-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
