# Generated by Django 5.2.8 on 2025-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_open_for_gigs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_role',
            field=models.CharField(blank=True, choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('WICKET_KEEPER', 'Wicket Keeper'), ('ALL_ROUNDER', 'All Rounder'), ('ANY', 'Any Role')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_role',
            field=models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('WICKET_KEEPER', 'Wicket Keeper'), ('ALL_ROUNDER', 'All Rounder'), ('ANY', 'Any Role')], default='ANY', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='total_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_wickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
