# Generated by Django 5.2.8 on 2025-12-02 18:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='HELD', max_length=20)),
                ('release_condition', models.TextField(help_text='Condition for payment release')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Escrow Transaction',
                'verbose_name_plural': 'Escrow Transactions',
                'db_table': 'escrow_transactions',
            },
        ),
        migrations.CreateModel(
            name='GroundCheckin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('user_lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('user_long', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('is_successful', models.BooleanField(default=False)),
                ('distance_from_venue', models.FloatField(blank=True, help_text='Distance in meters', null=True)),
            ],
            options={
                'verbose_name': 'Ground Check-in',
                'verbose_name_plural': 'Ground Check-ins',
                'db_table': 'ground_checkins',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('SOLO_MIX', 'Solo Mix'), ('TEAM_VS_TEAM', 'Team vs Team')], max_length=20)),
                ('ground_status', models.CharField(choices=[('BOOKED', 'Booked'), ('SECURED', 'Secured'), ('UNSECURED', 'Unsecured')], default='UNSECURED', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('total_slots', models.IntegerField(help_text='Total player slots available', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)])),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacancy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('looking_for_role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All Rounder'), ('WICKET_KEEPER', 'Wicket Keeper'), ('ANY', 'Any Role')], default='ANY', max_length=20)),
                ('count_needed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_per_head', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=20)),
                ('filled_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'db_table': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('venue_type', models.CharField(choices=[('BOX_CRICKET', 'Box Cricket'), ('PAID_OPEN', 'Paid Open'), ('FREE_LOCAL', 'Free Local')], max_length=20)),
                ('booking_mode', models.CharField(choices=[('IN_APP_PAY', 'In-App Payment'), ('RECEIPT_UPLOAD', 'Receipt Upload'), ('GPS_CHECKIN', 'GPS Check-in')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('gps_lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('gps_long', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('avg_cost_per_hour', models.IntegerField(help_text='Average cost in local currency', validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'db_table': 'venues',
            },
        ),
    ]
