# Generated by Django 5.2.8 on 2025-12-17 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ground_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SECURED', 'Secured'), ('BOOKED', 'Booked')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='host_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_matches', to='matches.club'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('SOLO_MIX', 'Solo Mix'), ('TEAM_VS_TEAM', 'Team vs Team')], default='SOLO_MIX', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_matches', to='matches.club'),
        ),
        migrations.AddField(
            model_name='turf',
            name='booking_mode',
            field=models.CharField(choices=[('INSTANT', 'Instant Booking'), ('REQUEST', 'Captain Request')], default='REQUEST', max_length=20),
        ),
        migrations.AddField(
            model_name='turf',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='gps_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='venue_type',
            field=models.CharField(choices=[('BOX', 'Box'), ('OPEN', 'Open Ground')], default='BOX', max_length=20),
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='HELD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='matches.match')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroundCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_lat', models.FloatField()),
                ('user_long', models.FloatField()),
                ('distance_meters', models.FloatField()),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_checkins', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('winning_team_name', models.CharField(blank=True, max_length=255)),
                ('summary_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_needed', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('WICKET_KEEPER', 'Wicket Keeper'), ('ALL_ROUNDER', 'All Rounder'), ('ANY', 'Any Role')], default='ANY', max_length=20)),
                ('count_needed', models.PositiveIntegerField()),
                ('cost_per_head', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('match', 'user')},
            },
        ),
    ]
