# Generated by Django 5.2.8 on 2025-12-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groundcheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='host_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_matches', to='users.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiting_matches', to='users.team'),
        ),
        migrations.AddField(
            model_name='groundcheckin',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='matches.match'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_transactions', to='matches.match'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='matches.match'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['venue_type'], name='venues_venue_t_e71370_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['is_verified'], name='venues_is_veri_a501ec_idx'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.venue'),
        ),
        migrations.AddIndex(
            model_name='groundcheckin',
            index=models.Index(fields=['match', 'user'], name='ground_chec_match_i_c4f0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='groundcheckin',
            index=models.Index(fields=['checkin_time'], name='ground_chec_checkin_96a2f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groundcheckin',
            unique_together={('match', 'user')},
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status'], name='escrow_tran_status_e7bf77_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['match', 'payer'], name='escrow_tran_match_i_c90963_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status'], name='vacancies_status_d0456c_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['match', 'status'], name='vacancies_match_i_359829_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['start_time'], name='matches_start_t_f662c7_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type'], name='matches_match_t_0c6248_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['ground_status'], name='matches_ground__d2ff1b_idx'),
        ),
    ]
